language: android

jdk:
  - oraclejdk8

android:
  components:
    # Use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    - build-tools-25.0.2
    - android-25

    # Additional components
    - extra-android-m2repository
    - extra-android-support

  licenses:
    - 'android-sdk-license.*'

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

before_script:
  - chmod +x scripts/publishToBintray.sh
  - chmod +x gradlew

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - ./gradlew build jacocoTestReport

after_success:
  - scripts/publishToBintray.sh
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
  global:
    - secure: "mX4QQExx8Y/qH7aLRuGGG47oJoq0/nGtH20L+VbdvlH0CVrXtlMx8WxdFXz6AZVJ1KJ+FeEUV33pTCFzzpFy/ufrX2LuinI8J2W5p1TubmSsZozO2Fip0aOqzooj3/hEjgdHWehvfyt8fOrvYFd2wrVUzFXItA4ulSZFuNy7D+l9abKeEcVlmGg50ulPW8+f+C8tEyR3rF4TFFOZPNnunuKAheuv3cfktkwr8DRFjkAX8LeZXq9cyaLbvZWhDx8nKe6Ib0GNAuc1D/BRoJ2kVkLlt3StPrQ/yD+4AFJUuW/lKLfQkBdlxFPW1rKGImy723NwcPsWDCK55yRM9KNOAZzjSCdBeRlV6eQV4lNID2foBppBu65eImbIrgJEG7LtW3kBSxFkZpjx/eOFe9aWNhtgsPY6d320CLpWpXhqZdevXVudK74EsDSPZDndkQo6pRY+T9IK+jWXXT56bu9J6ktNEkZJAiGfmT3hwmki+2Fba2kmOLu0v9c/VCOSakaoxqGZWm7itz9xHArNlJhG9cDxVEd7D1nzkLwyHx+3QO9bEkVtvG5w3c+XKGwMtIAc6d8dwxnTYcZKBWJWuGf8VKJBM66F1hg/EURCLljUsCsqHVETjr5sXPaCY6nCA7hqVuUQerx4IfF5wWm+PRVfQbZ0DCS2f/fSwJX9vjbGSuI="
    - secure: "AOXcZq647sHun6/9gtbIRQBpUvEd6ViI21vK8+ki8vzLMu/PNuF14FJ1Q2vg56Opw12G05hvuGZwuXUf/0bTKv97ooYtEeQchPi6jeDLxN4XMPtV79Xrja/l1rvvTt4MjpQCfmIiJCecNbhlKy8eyM5XclCg/rbp0Dzft10931mWUYvIeCW/U6gdsKT1n9QkP11mp4jg+zHzqKpjj2bkwGnl2j60gLgFWi8uT/fR+O6Uw36I7U3aUOFVAxN364nt6nDGvEFGPv0VbCx176pu63fTGDgK0wjoUCTeYzLanv+X6lmFFKxST7Y8xq5NHq44g0sTVc5R/nwikqJ1YaaWu8bjBFF4fukEwPQh2oTrziKZXuzkXD5av7lU/AWgsdy6H9s8/83/XLdQVpDBD7Et6+Wuj7QlaI63RGk0RADmpd9F9/IFXwr5y02XnMkfJJxgmD5tOBv8j/B/B3COik9lY2ePI6XuPgRFAj8gSc+ODLV1OMrw/FJDVVJs9g4UQsRZ+WTQq94qCN/N3oCdTssujgAxCywW/by57Cr8gdKwK8TGNXSRrZJ1yky4ocQv1dN9O0Btt6i8OOWIxK3S0tfpqqsMNA4bPslZG4WjTUaILPRIum9zEO2INKtt55+OV6lJTbrQ43Jw35dmuxGMySyxZVzzxvQhORiip5y89XBrV6s="
    - secure: "J738Tlffpv5dxFHxzrDUAKSdMPFjgWDdSnGvAWdf7M0/7qvmoTmNOaqIrQk6/UN5TEBeB/Fuqm4cA0HSTK5YSaf9F4xPCvxTkppGVoSEdzc7SxBCeksdR3ule+N2VfJME1Hci/vkyE5n0rzng4r9cBfxT4pvbXMZLVpcdrfSHoBZdMlVjgDTK2N3SXVZKUU/+viH3U/joJOC8MQp6qQbt5m6YJZ1mouFmdxvm9HsZ956BEv6JDnubimH3zqWfx3eWIp81vpjY74wfsMjm0KqarOu6L4CKtTu7ytoDR1sQiqljsuQcDRL7sW3z+tXVrjrv3Yxa+dV0K/gb+z2J68oclFkFPEf80LwbaeOOjPNNlQ7sjoxq3/1+NFEe9vafgZgS1jL10rwPc5Y+60cL2Pqf2p+XnW8X9wopx1iwhzv6kSjjb8CfmpiUa0gd6qb8BcdW3E9428SdgMggPG3o8l3DYBWuq0JkUCVEgfNUwsFzBynav49y1KlpBEDlTWTVa+Qc6QFF+H4zkXODN63ritpM+kKGlNeVMy85Ioe/evbH5YNtCpCsyAbWFDSrczVLUWM9U5QscndZ3Eehh4+NsytHHWyRz9Ffky+JE8ZsZCqQmOjgKWtF8/Q8x+zHZmwkZWeKWkVSUmr9xahBd9Y9Kk0l/Bmp7R++K0Yhx/mRfrdbEI="
    - secure: "U4Ou8098jJKS2W4bTwDqCBQY84eeLND5cIZRNFOIzKZa4erRYAMOIQdDTTfUYwDGcIPFDzThQg0a4s5+G+LA541n/hgw1F+uarcwD2MHXywdquQgzvAJdDQViYeOIji2lFI9hYMR0YkricvepYlvDoSq3llQARTNEsPnqgbKx2KCH8RxHl8IdbVruOfPI1Z0t52x771+mHVtwTwIwd9HxnTzQ/GOyAQatQLkdhB/Nva34zFlxARsfaSHBKUjStiLkgauqrEu3Wnk6kkgm/cDTBo0I8XCwy3mRpr9v2Qjk8w5WHD8PlPI49lafkdfLk3nGpAGK8PUWHt1VjumVS3bqMUvYM4qucm6VozF43oOhxwvqA9pvYrRSaPVpwYbQ6Un2wWBv3FzEXQVIJ9TLL69inbHPsuAc2aNYCskzV9cOwx7pUcwprgk96FjS0kEnWNSofQPLKx5uAYc6rdrfmiMk1//iUvKACvHUZGzHUlanPOSYlI51sX++MC4SjtcGRaKug5vZTDiQKcPNp4qxaIJ6uwb5mbIOD9Z526xpIjbyWA4M/5SyM9aX+oemzuqBxCO3BipMqQTpuHTqonZWZGsSaAAYlUT59yKNHQ1rMS2ICJJztRNg8vq2i8Ekajdt17chF7ssjWUq/L0GbWL7kJg1hO4aEVUJQJG47qlQh+5ous="
    - secure: "iSfq7GmFQBMP5IysIC5/r+it+3Av4+W6wNvKm7jB+oLBtXUpe/oH7P7kam2Y51nQDrJy2mUo32BaeyBYCZlQa/HDiq2KMgjqEgx+G7bM5OkG/iWNsSb3hFhQit6W7QpjeqLXeYRT78k8C9mO7j8aLT6s9hi2W4orzs3Cmvm72Mga8Tr/Ka6JVL3nujABmSnDWdMym6s2NW7dOhaSEGOrjqDlTTL2ac/iI19YL6z6MgyfwSpilrQaVVD0Qzb48n7QlPun8ZCoTQ2OsnZH0f+XaAuGtffGlMMUnWrV0CwJ2pk2sx/JyD0MnK7hxzMLuwaoIxLwTr5xAGaCLCZy1mjpKlqQqwbZmfQcJZMSE0Kh92JYiESD6PJkrfVOxSG7L6wepjXxRRo++6s5n725kCKg2q4/XtOo1IV9Psq036z2pxjG8PuHI2+FRszu2tQASb2eojDjhrNJUbkcm8a2RJN3XL9EiYyOmdEP8otGD9kjxaap/p8soatKuVQDunju9N1UDceRbw6IlSjXMoMr/EzGvlerBGAEcWjSEWTLlXjCh2aJvL9gYqAGL4foxJ+MIN0jxv9bZQjH+2HG0/ZqSqWdbS4yhTMQQxuvyVyDDWdPeikFzzxCip5T9u5hyTV27AsQu9Ai/j2weCeH4yj8W97o8q99flwsT0PZW+t8X/AQSJA="


